export default [
  {
    color: '#95E49F',
    first_name: 'Test',
    id: '1',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#D0FDE0',
    first_name: 'Test',
    id: '2',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#94DCBE',
    first_name: 'Test',
    id: '3',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#6A3777',
    first_name: 'Test',
    id: '4',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#29CAE4',
    first_name: 'Test',
    id: '5',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#2D68D2',
    first_name: 'Test',
    id: '6',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#94072D',
    first_name: 'Test',
    id: '7',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#9C77A9',
    first_name: 'Test',
    id: '8',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#67A43C',
    first_name: 'Test',
    id: '9',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
  {
    color: '#D95E22',
    first_name: 'Test',
    id: '10',
    last_name: 'Dev',
    sub_title: 'sub title',
    title: 'title title title title title title test test',
  },
];
